# Generated by Django 3.1.7 on 2021-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
